name: nlp-project
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - nltk
  - requests
  - python-dotenv
  - pandas
  - scipy
  - scikit-learn
  - gensim
  - transformers
  - fuzzywuzzy
  - pip
    - torch
